### ISSUE TITLE
Feature request: adding more than only individual records related to a location

### ISSUE THREAD

**Issue by hartenthaler** [vesta-webtrees-2-custom-modules/vesta_clippings_cart#16]
There are for example 6 persons related to a location record, but no families; when adding them to the clipping cart only I-records (and sources and location records and notes ...) are added, but no F (family records). I would like to have an additional option to add not only these 6 individuals but their families too (parents, siblings, partners, children).

**Comment by ric2016** [comment]
Option added in latest release 2.0.17.1.0.
