### ISSUE TITLE
Feature request: more options to select individuals for the clipping cart

### ISSUE THREAD

**Issue by hartenthaler** [vesta-webtrees-2-custom-modules/vesta_clippings_cart#17]
Zur Visualisierung von GEDCOM-Datenmengen gibt es eine schöne Anwendung: [Topographic Attribute Maps](https://github.com/rpreiner/tam). Ich stehe dazu im Kontakt mit [@EW.H](https://github.com/huhwt), der diese Darstellungsmöglichkeit gerne für webtrees erschließen möchte.

Um die zu visualisierende Datenmenge auszuwählen, eignet sich aus meiner Sicht der Sammelbehälter ganz gut. Nun möchte ich die bereits vorhandenen Optionen (Personen mit Familie/Vorfahren/Nachkommen/Bewohner eines Ortes/...) um neue erweitern:
- alle unverbundenen Personen eines Trees
- alle Personen mit gleichem Nachnamen in einem Tree
- alle Heiratsketten in einem Tree (also Ketten von Partnern von Partnern von Partnern)
- alle Ahnenkreise in einem Tree (also etwa alle Verbindungen, die zu Ahnenschwund führen).

Dazu gibt es drei mögliche Vorgehensweisen:
- ich entwickle ein eigenes Clipping Cart Modul als Erweiterung des bestehenden
- ich entwickle die dazu nötigen Funktionen als Pull Request für Dein Vesta-Modul
- ich entwickle die dazu nötigen Funktionen als Pull Request für das webtrees Core-Modul

Was schlägst Du vor? Was meinst Du dazu?

**Comment by ric2016** [comment]
Das Vesta-Clipping-Cart-Modul war ursprünglich nur zur Einbindung der Gemeinsamen Orte gedacht und könnte bei entsprechendem Support dafür in webtrees irgendwann obsolet werden. Es ist deswegen für solche Erweiterungen eher nicht geeignet.

Grundsätzlich schadet ein Versuch nicht, diese Funktionalität direkt in webtrees unterzubringen, denke ich. Wenn das nicht klappen sollte, ist wohl ein eigenes Modul die beste Lösung.

Was man vielleicht eigentlich gerne hätte - aber das führt aktuell wohl zu weit: Eine durch verschiedene Module konfigurierbare Suche nach Personen (oder auch anderen Gedcom-Objekten), die u.a. die genannten Optionen anbietet; kombiniert mit der Möglichkeit, die Suchergebnisse dann für verschiedene Zwecke zu verwenden (Listenansichten, Pdf-Reports, Clipping Cart, ...).

**Comment by ric2016** [comment]
[Weiteres im Forum.](https://www.webtrees.net/index.php/en/forum/4-customising/36230-enhanced-clippings-cart)

**Comment by hartenthaler** [comment]
Ja, das hatte ich mir auch so gedacht. Aus meiner Sicht könnte der Sammelbehälter eine zentrale Datendrehscheibe sein. Ich habe das mal grafisch aufbereitet und im [Forum](https://www.webtrees.net/index.php/en/forum/4-customising/36230-enhanced-clippings-cart) zur Diskussion gestellt. Scheint aber keine Resonanz zu finden oder ich habe es zu unverständlich formuliert. Ich werde mich hier mal etwas einarbeiten und einen ersten Versuch umsetzen.
