### ISSUE TITLE
"Delete an item in clippings cart" does not work

### ISSUE THREAD

**Issue by hartenthaler** [vesta-webtrees-2-custom-modules/vesta_clippings_cart#7]
If you add something to the clippings cart and then open the clippings cart there is a second column where you can delete items of this list. But when clicking, this results in the error message "Module clippings does not exist". Maybe there is somewhere a reference to the standard clippings module.

**Comment by ric2016** [comment]
Yes, there is such a reference (in one other place as well: When canceling the clippings cart download).
I hope to get this fixed via https://github.com/fisharebest/webtrees/pull/3592 (this will still require a new Vesta module release).

**Comment by ric2016** [comment]
Fixed in latest release (with a workaround until the PR is accepted, I'll leave the issue open until then).

**Comment by hartenthaler** [comment]
This issue is again open!

**Comment by ric2016** [comment]
I cannot reproduce this, deleting single entries from the Vesta clippings cart still works for me.
